name: Publish distributions to PyPi and TestPyPi
on: push

jobs:
    buildpub:
        name: Build and publish
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Set up Python 3.7
          uses: actions/setup-python@v1
          with:
            python-version: '3.x'

        - name: Install deps
          run: |
            python -m pip install --upgrade pip
            pip install Soundfile numpy

        - name: Build
          run: >-
            python setup.py sdist build
            
        - name: Publish to PyPi
          env:
            TWINE_USERNAME: ${{ secrets.pypi_username }}
            TWINE_PASSOWRD: ${{ secrets.pypi_password }}
          if: startsWith(github.event.ref, 'refs/tags')
          run:
            python setup.py sdist bdist_wheel
            twine upload dist/*
            
