name: Publish distributions to PyPi and TestPyPi
on: push

jobs:
    buildpub:
        name: Build and publish
        runs-on: ubuntu-18.04
        steps:
        - uses: actions/checkout@master
        - name: Set up Python 3.7
          uses: actions/setup-python@v1
          with:
            python-version: 3.7
        - name: Build
          run: >-
            python setup.py sdist build
            
        - name: Publish distribution 📦 to Test PyPI
          uses: pypa/gh-action-pypi-publish@master
          with:
            password: ${{ secrets.test_pypi_password }}
            repository_url: https://test.pypi.org/legacy/
        - name: Publish distribution 📦 to PyPI
          if: startsWith(github.event.ref, 'refs/tags')
          uses: pypa/gh-action-pypi-publish@master
          with:
            password: ${{ secrets.pypi_password }}
            
