name: run tests automatically each push
on: push

jobs:
    tester:
        name: Use pytest to run tests each push
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: '3.x'

        - name: Install deps
          run: |
            sudo apt-get install libsndfile1
            wget "https://github.com/flucoma/flucoma-cli/releases/download/1.0.0-RC1/FluidCorpusManipulation_CLI_Linux_1_0_0-RC1.tar.gz"
            tar -xvf FluidCorpusManipulation_CLI_Linux_1_0_0-RC1.tar.gz
            echo "::add-path::./FluidCorpusManipulation/bin/"
            python -m pip install --upgrade pip
            pip install setuptools wheel pytest
            pip install -e .

        - name: test
          run: | 
            pytest
