name: run tests automatically each push
on: push

jobs:
    tester:
        name: Use pytest to run tests each push
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: '3.x'

        - name: Install deps
          run: |
            python -m pip install --upgrade pip
            pip install setuptools wheel twine
            pip install Soundfile numpy

        - name: test
          run: | 
            pytest
