name: run tests automatically each push
on: push

jobs:
    tester:
        name: Use pytest to run tests each push
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: '3.x'

        - name: Install Dependencies
          run: |
            git clone "https://github.com/flucoma/flucoma-cli.git"
            cd flucoma-cli
            mkdir -p build && cd build
            cmake ..
            make install
            cd ..
            echo "::add-path::$GITHUB_WORKSPACE/flucoma-cli/release-packaging/FluidCorpusManipulation/bin"
            
        - name: Install Libraries
          run: sudo apt-get install libsndfile1

        - name: Setup Python
          run: |
            cd $GITHUB_WORKSPACE
            ls $GITHUB_WORKSPACE/flucoma-cli/
            echo $PATH
            python -m pip install --upgrade pip
            pip install setuptools wheel pytest
            pip install -e .
            
        - name: Run Tests
          run: pytest
